backend:
  name: github
  repo: kaliaAldin/cess_website2
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: english
    label: English
    files:
      - file: "src/data/en.json"
        name: en
        label: English Content
        format: json
        fields:
          - { name: title, label: Title, widget: string }
